// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUgIcG8tE5hcvJGpJ1dVsMUrqnENclE_A',
    appId: '1:1032625658923:web:dcb05b44435de1f52d5e6e',
    messagingSenderId: '1032625658923',
    projectId: 'module-2-firebase',
    authDomain: 'module-2-firebase.firebaseapp.com',
    storageBucket: 'module-2-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYfd8NfKQdSu1lkZ8O4iP0WctN7nsShY',
    appId: '1:1032625658923:android:e25794d79f279f152d5e6e',
    messagingSenderId: '1032625658923',
    projectId: 'module-2-firebase',
    storageBucket: 'module-2-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnq0gB4KIJAfyHwBfOPZzHSS3pt3vrT4',
    appId: '1:1032625658923:ios:780acb1e3ad98d9e2d5e6e',
    messagingSenderId: '1032625658923',
    projectId: 'module-2-firebase',
    storageBucket: 'module-2-firebase.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnq0gB4KIJAfyHwBfOPZzHSS3pt3vrT4',
    appId: '1:1032625658923:ios:6279c51edfae7f432d5e6e',
    messagingSenderId: '1032625658923',
    projectId: 'module-2-firebase',
    storageBucket: 'module-2-firebase.appspot.com',
    iosBundleId: 'com.example.calculator.RunnerTests',
  );
}
